name: Build and Release Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Quellcode holen ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Python / PlatformIO vorbereiten ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      # --- Firmware bauen ---
      - name: Build firmware
        run: pio run

      # --- Versionstext erzeugen ---
      - name: Generate version.txt
        run: echo "v${{ github.run_number }}" > version.txt

      # --- Git-Tags sicherstellen ---
      - name: Ensure initial tag exists
        run: |
          git fetch --tags
          if [ -z "$(git tag)" ]; then
            echo "Kein Tag gefunden, erstelle Start-Tag v0"
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git tag v0
            git push origin v0
          fi

      # --- Neues Tag erstellen und pushen ---
      - name: Create and push new tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}

      # --- Automatischer Changelog ---
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: '{"template":"## Änderungen\n\n{{CHANGELOG}}"}'
          toTag: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- GitHub Release erstellen ---
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Firmware v${{ github.run_number }}"
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            .pio/build/esp32dev/firmware.bin
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
