name: Build and Release Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Code holen ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Python / PlatformIO vorbereiten ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      # --- Firmware bauen ---
      - name: Build firmware
        run: pio run

      # --- Versionstext erzeugen ---
      - name: Generate version.txt
        run: echo "v${{ github.run_number }}" > version.txt

      # --- Automatischer Changelog ohne API-Key ---
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: '{"template":"## Änderungen\n\n{{CHANGELOG}}"}'
          toTag: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- GitHub Release erstellen ---
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Firmware v${{ github.run_number }}"
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            .pio/build/esp32dev/firmware.bin
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
